### ISSUE TITLE
Stuck in Chapter 5

### ISSUE THREAD

**Issue by kenandavis** [learn-javascript-courses/programming-javascript-applications#1]
Hi Eric,

So, in Chapter 5 of Programming Javascript Applications, I'm a little stuck. After cloning TinyApp, it says to "require() it and initialize your app." But I don't understand what file I'm supposed to do that in and where in the folder structure should that file go.

Any guidance would be greatly appreciated. I would also love if there was some source code for the book that I could refer to when I get lost.

Thanks and loving the book so far! 
Kenan

**Comment by ericelliott** [comment]
Thank you for your question! This example isn't intended as a step-by-step guide to build an app, but rather as a general introduction to Tinyapp. There's another explanation in the [Tinyapp getting started guide](https://github.com/ericelliott/tinyapp/blob/master/README.md#getting-started).

To make sure Tinyapp is installed for your particular app:

```
npm install --save tinyapp
```

For more on how to apply Tinyapp to help build a real application, the ["Events by Example"](http://chimera.labs.oreilly.com/books/1234000000262/ch05.html#events_id3) section of Chapter 5 revisits [the Guestlist app from Chapter four](http://chimera.labs.oreilly.com/books/1234000000262/ch04.html#defining_the_app). Those examples tell you which files to modify and how.

~ee
